<html>
<head>
  <script type="text/javascript">
    // this test only makes sense in the context of the async loader since a throw in the 
    // middle of a synchronous load sequence will kill the remainder of the sequence
    dojoConfig= {
      has:{
        "dojo-sync-loader":0
      }
    };
    if(location.search=="?noCatch"){
      dojoConfig.has["dojo-loader-catches"]= 0;
      dojoConfig.has["dojo-error-api"]= 0;
    }else{
      dojoConfig.has["dojo-loader-catches"]= 1;
      dojoConfig.has["dojo-error-api"]= 1;
    }
  </script>
  <script type="text/javascript" src="../../../dojo.js" data-dojo-config="isDebug:1, async:1"></script>
  <script type="text/javascript">
    require(["dojo", "doh", "dojo/has"], function(dojo, doh, has) {
      dojo.ready(function(){
        define("dojo/tests/_base/loader/OkModule1", [], function(){
          return "OkModule1";
        });
        
        // define a module that will throw
        define("dojo/tests/_base/loader/throwModule", [], function(){
          // this will throw
          return someVariableThatDoesNotExist;
        });
        
        define("dojo/tests/_base/loader/OkModule2", [], function(){
          return "OkModule2";
        });

        // define a module that will throw
        define("dojo/tests/_base/loader/throwModule1", [], function(){
          // this will throw
          return someVariableThatDoesNotExist;
        });

        // the loader works the same with or without the catch api if no onError listeners say its ok to continue
        doh.register("no-catch-api", [
          function expectDojoConfig(t) {
            // require a module that will throw bracketed by two modules that are OK
            var callbackCalled= 0;
            try{
              require([
                "dojo/tests/_base/loader/OkModule1", 
                "dojo/tests/_base/loader/throwModule", 
                "dojo/tests/_base/loader/OkModule2"], function(m1, m2, m3){
                callbackCalled= 1;
              });
              // should never get here
              t.is(1, 2);
            }catch(e){
            }

            t.is(callbackCalled, 0);
            t.is(require("dojo/tests/_base/loader/OkModule1"), "OkModule1");
            if(has("dojo-loader-catches")){
              t.is(require.modules["dojo*tests/_base/loader/throwModule"].executed.value, "exec-threw");
            }else{
              t.is(require.modules["dojo*tests/_base/loader/throwModule"].executed.value, "executing");
            }

            // the loader is still alive, we can retry to load OkModule2 and succeed...
            t.is(require.modules["dojo*tests/_base/loader/OkModule2"].executed, 0);
        
            // still alive...
            require(["dojo/tests/_base/loader/OkModule1", "dojo/tests/_base/loader/OkModule2"], function(m1, m2){
              t.is(m1, "OkModule1");
              t.is(m2, "OkModule2");
              callbackCalled= 1;
            });
            t.is(callbackCalled, 1);

            // insert an error handler that fixes the error and signals to continue...
            if(has("dojo-error-api")){
              function handler(messageId, args){
                t.is(messageId, "loader/exec");
                t.is(args[0].pqn, "dojo*tests/_base/loader/throwModule1");
                args[0].result= "result provided by error handler";
                return true;
              }
              var handle= require.on("error", handler);

              t.is(require.errorListeners.length, 1);
              t.is(require.errorListeners[0], handler);
  
              require(["dojo/tests/_base/loader/throwModule1"], function(m){
                t.is(m, "result provided by error handler");
              });

              handle.remove();
              t.is(require.errorListeners.length, 0);
            }
          }
        ]);
        doh.runOnLoad();
      });
    });
  </script>
</head>
<body>
</body>
</html>
